#!/usr/bin/python3

import subprocess as sp
import os
import shutil as sh
import re
import sys

name = sys.argv[1]
os.stat(name)
try:
	os.stat(name+'.enc')
	if re.match(r'^[Nn]', input('Overwrite old ciphertext? [Y/n] ')):
		print("Aborting..")
		exit(0)
	else:
		os.remove(name+'.enc')
except FileNotFoundError:
	pass

tarP = sp.run(['tar','-czavf','-','--',name],
	stdout=sp.PIPE, check=True)
sslP = sp.run(['openssl','enc','-pbkdf2','-aes-256-cbc','-md','sha256',
	'-out',name+'.enc'],
	input=tarP.stdout, close_fds=True, check=True)
if re.match(r'^([Yy].*)?$', input('Delete plaintext? [Y/n] ')):
	sh.rmtree(name)








