#!/usr/bin/env python3
import os
import subprocess as sp
import sys
import argparse

parser = argparse.ArgumentParser(description='sed on all files in a directory')
parser.add_argument('operation')
parser.add_argument('dir', nargs='?')
args = parser.parse_args()

if not args.dir: dir = '.'
else: dir = args.dir

for dirpath, dirnames, filenames in os.walk(dir):
	for filename in filenames:
		p = sp.run(['file', fullpath], capture_output=True)
		if not re.match(r'text', p.stdout.decode()):
			continue # only modify text files
		fullpath = os.path.join(dirpath, filename)
		sp.Popen(['sed', '-i.bak', args.operation, fullpath])