#!/usr/bin/env python3
import os
import subprocess
import argparse

# Reference implementaion for creating new scripts

parser = argparse.ArgumentParser(description='Edit a text file')
parser.add_argument('-d', '--visual', action='store_true')
parser.add_argument('-t', '--terminal', action='store_true')
parser.add_argument('-l', '--line', type=int)
parser.add_argument('-s', '--synchronous', action='store_true')
parser.add_argument('file')
args = parser.parse_args()

if args.visual or ('DISPLAY' in os.environ and not args.terminal):
	command = ['cdoedit']
	sync = args.synchronous
	if args.line is not None:
		command += ['-l', str(args.line)]
	command += [args.file]
else:
	sync = True
	if args.line is not None:
		command = ['nano', '+'+str(args.line), args.file]
	else:
		command = ['nano', args.file]

if sync:
	os.execvp(command[0], command)
else:
	subprocess.Popen(command)
