#!/usr/bin/env python3
import os
import argparse

parser = argparse.ArgumentParser(description='Find file/line recursively jump to it, wraps jumplist and grep')
parser.add_argument('query')
parser.add_argument('location', nargs='?')
args = parser.parse_args()

# -H - filenames, -n - line numbers, -r - recursive, -I - ignore binary
command = ['jumplist', 'grep', '-HnrI', args.query]
if args.location is not None:
	command.extend([args.location])

os.execvp(command[0], command)
