#!/usr/bin/env python3
import os
import subprocess
import sys
import argparse
import re

parser = argparse.ArgumentParser(description='Install a package that contains a specified file')
parser.add_argument('file')
args = parser.parse_args()

search = subprocess.Popen(['apt-file', 'search', os.path.join('', args.file)], stdout=subprocess.PIPE, stdin=subprocess.DEVNULL)
search.wait()
line = search.stdout.readline()
pkgMatch = re.match(r'([^:]+):', line.decode())
if pkgMatch:
	print('File '+args.file+' found in '+pkgMatch.group(1)+'. Installing...')
	command = ['sudo', 'apt-get', 'install', '-y']
	command.append(pkgMatch.group(1))
	subprocess.Popen(command, stdout=subprocess.PIPE).wait()
else:
	print('File '+args.file+' not provided by apt.', file=sys.stderr)
