#!/usr/bin/env python3
import os
import subprocess
import argparse
import sys
import re

def lineCount(file):
	with open(file) as f:
		return f.read().count('\n')

parser = argparse.ArgumentParser(description='Jump to lines selected from the output of a command')
parser.add_argument('-e', '--exclude-stderr', action='store_true')
parser.add_argument('command', nargs=argparse.REMAINDER)
args = parser.parse_args()

if args.exclude_stderr:
	stderr = None
else:
	stderr = subprocess.STDOUT

listingProcess = subprocess.Popen(args.command, stdin=subprocess.DEVNULL, stdout=subprocess.PIPE, stderr=stderr)

entries = []
tail = False # copy indented lines after entry
with listingProcess.stdout as inputFile:
	for rawEntry in inputFile.readlines():
		entry = rawEntry.decode()
		# Doesn't work if filename contains colon or a whitespace character
		entryData1 = re.match(r'^([^:\s]+):([0-9]+):([0-9]+:)?.*$', entry)
		entryData2 = re.match(r'^\s*File "([^"]+)", line ([0-9]+).*$', entry)
		if entryData1 is not None:
			print(str(len(entries)), entry, sep=':\t', end='')
			entries.append([[entry], entryData1.group(1), entryData1.group(2), []])
			tail = True
		elif entryData2 is not None:
			print(str(len(entries)), entry, sep=':\t', end='')
			entries.append([[entry], entryData2.group(1), entryData2.group(2), []])
			tail = True
		elif re.match('^[^\s]', entry) is None and tail:
			print('\t'+entry, end='')
			if len(entries) > 0:
				entries[-1][0] += [entry]
		else:
			print('\t'+entry, end='')
			tail = False

if len(entries) == 0:
	sys.exit(0)

try:
	userInputs = input('> ')
	origLines = dict()
	for userInput in userInputs.split(' '):
		splitInput = userInput.split('-', maxsplit=2)
		if splitInput == ['all'] or splitInput == ['']:
			start = 0
			end = len(entries) - 1
		elif len(splitInput) == 1:
			start = int(splitInput[0])
			end = start
		else:
			start = int(splitInput[0])
			end = int(splitInput[1])
		for i in range(start, end+1):
			for line in entries[i][0]:
				print(line, end='')
			filename = entries[i][1]
			line = int(entries[i][2])
			if filename in origLines:
				# Account for changes made on prior lines, assume all changes were made above our current location.
				line += lineCount(filename) - origLines[filename]
			else:
				origLines[filename] = lineCount(filename)
			p = subprocess.Popen(['edit', '-s', '-l', str(line), filename])
			p.wait()
except KeyboardInterrupt:
	# Ensure we flush before we exit otherwise the shell may print the prompt first
	# TODO: This sometimes fails, investigate
	print(flush=True)
