#!/usr/bin/env python3
import os
import subprocess
import sys
import argparse
import re

parser = argparse.ArgumentParser(description='Parse meson output and install required packages')
args = parser.parse_args()

toInstall = []
p = subprocess.Popen(['meson', 'build/'], stdout=subprocess.PIPE, stderr=subprocess.STDOUT, stdin=subprocess.DEVNULL)
p.wait()
for line in p.stdout:
	m = re.match(r'([^:]+) ([^\s]+) found: NO', line.decode())
	if m:
		search = subprocess.Popen(['apt-file', 'search', m.group(2)+'.pc'], stdout=subprocess.PIPE, stdin=subprocess.DEVNULL)
		search.wait()
		line = search.stdout.readline()
		pkgMatch = re.match(r'([^:]+):', line.decode())
		if pkgMatch:
			toInstall.append(pkgMatch.group(1))
			print('Package '+m.group(2)+' found in '+pkgMatch.group(1))
		else:
			print('Package '+m.group(2)+' not supported by apt.', file=stderr)
			exit(1)

print(toInstall)
for pkg in toInstall:
	command = ['sudo', 'apt-get', 'install', '-y']
	command.append(pkg)
	subprocess.Popen(command, stdout=subprocess.PIPE).wait()
