#!/usr/bin/env python3
import backup

pcs = ['peter', 'isaac']
pc_parts = ['home', 'root']
for pc in pcs:
    for part in pc_parts:
        run_tar_backup(pc, part)

servers = ['william', 'algernon', 'cullen']

run_tar_backup('peter', 'home')
run_tar_backup('isaac', 'home')
run_tar_backup('peter', 'root')
run_tar_backup('isaac', 'root')

# sp.run(['rsync', '-Pnva', '/mnt/9/', '/mnt/3/'])
# sp.run(['rsync', '-Pnva', '/mnt/9/', 'cdo@william:/srv/files/cdo/'])
