#!/bin/zsh

f=$1
ft=`file -b --mime-type $f`
if [[ $f =~ '\.tar\.gz$' ]]; then
	nf=`tar --list -f $f | head -n1`
	tar -xzf $f
	cd $nf
elif [[ $ft =~ '^text' ]]; then
	edit $f
elif [[ $ft =~ '^inode/x-empty' ]]; then
	edit $f
elif [[ $ft =~ '^inode/directory' ]]; then
	cd $f
	ls
else
	1>&2 echo "could not open $f, type: $ft"
	return 1
fi
