#!/bin/zsh

scpt="$1"
scpt=`which "$scpt"`
if [[ `head -c 2 "$scpt"` == '#!' ]]; then
   function remove_trace() {
      sed -i 's%^#!/bin/zsh -x%#!/bin/zsh%' "$scpt"
   }
   remove_trace
   sed -i 's%^#!/bin/zsh%#!/bin/zsh -x%' "$scpt"
   trap remove_trace INT TERM EXIT
   eval "$@"
else
   echoeror "bad"
fi
