#!/usr/bin/env python3
import os
import subprocess
import argparse

parser = argparse.ArgumentParser(description='Open a web browser')
parser.add_argument('-d', '--visual', action='store_true')
parser.add_argument('-t', '--terminal', action='store_true')
parser.add_argument('-s', '--search', action='store_true')
parser.add_argument('-u', '--url', action='store_true')
parser.add_argument('-b', '--browser', nargs=1)

parser.add_argument('location')
args = parser.parse_args()

if args.search:
	url = 'http://duckduckgo.com/lite/search?q='+args.location
else:
	url = args.location

if args.visual or ('DISPLAY' in os.environ and not args.terminal):
	if args.browser is None:
		browser = 'firefox'
	else:
		browser = args.browser
	
	subprocess.Popen([browser, url])
else:
	if args.browser is None:
		browser = 'lynx'
	else:
		browser = args.browser
	
	os.execvp(browser, [browser, url])
